apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-benchmark
  template:
    metadata:
      labels:
        app: redis-benchmark
    spec:
      containers:
        - name: redis-benchmark
          image: lasdox/redis-benchmark:1.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: SENTINEL_MASTER_NAME
              value: "harness-redis"
            - name: INTERVAL_TIME_MILLIS
              value: "10000"
            - name: SENTINEL_ADDRS
              value: "redis-sentinel-harness-announce-0:26379,redis-sentinel-harness-announce-1:26379,redis-sentinel-harness-announce-2:26379"
